# Generated by Django 3.1.5 on 2021-03-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_boardmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'verbose_name': '게시판 멤버', 'verbose_name_plural': '게시판 멤버'},
        ),
    ]
