# Generated by Django 3.1.5 on 2021-03-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='유저메일')),
                ('contents', models.CharField(max_length=100, verbose_name='내용')),
            ],
        ),
    ]
