# Generated by Django 3.1.5 on 2021-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('mainphoto', models.ImageField(blank=True, default='images/None/no-image.jpg', null=True, upload_to='images/')),
                ('contents', models.TextField()),
            ],
        ),
    ]
