# Generated by Django 3.1.5 on 2021-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210306_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, default='images/None/no-image.jpg', null=True, upload_to='images/'),
        ),
    ]
