# Generated by Django 3.1.5 on 2021-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20210311_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='photo',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y%M%d'),
        ),
    ]
